### ISSUE TITLE
You should be able to get on a train with open doors by just walking in.

### ISSUE THREAD

**Issue by gpcf** [orwell96/advtrains#22]
This is a wishlist item. I've seen on my server that the current system of people getting on trains by right-clicking is counter-intuitive, people just try to walk in, similarly, you should get out walking out when doors are open.

**Comment by ValkyrieStella** [comment]
I like the idea, esp for automatic trains

**Comment by gbl08ma** [comment]
I agree. But care must be taken in the implementation to make sure that people passing by aren't pulled and attached to the train unless they really go in :wink:

As a related wishlist item, trains should have a floor. It's a bit bad to fall into the tracks when leaving a train, also all the platforms in my stations are raised by one block and this means that the flow right now goes like this: exit train -> get detached (you fall) -> you need to rise into the platform again.

I'm sure this is hard as one must play with the limitations of Minetest (in fact, ideally, one would be able to walk freely inside trains while they move, but said limitations get in the way). Perhaps said floor could only trigger when the doors are open.

I wonder how hard it would be for the Minetest devs to rework the player attachment system? One where the player can move (with WASD) relative to the attaching point, within the limits imposed by the surrounding objects (in this case, the train walls and floor), and the difference between the center of the attaching point and the player (i.e. the coordinates in the train referential) are maintained as the train moves, so that the player can't leave the train, but can move inside it?

**Comment by ValkyrieStella** [comment]
@gpcf you should make your own fork

**Comment by gpcf** [comment]
This would be nice. Maybe if you just stepped on the platform you would get on the train. I am more worried about people getting out getting in again by accident, but this should be preventable. 

If there's an actual platform at the stop, you already get out on the platform and not on the tracks. It just has to be the advtrains platform and it has to be directly adjacent to the track. 

@JamesTobin I already have my own fork, it just gets merged all the time into advtrains, I don't want to split the codebase.

**Comment by ValkyrieStella** [comment]
well stepping ON the patform, knowing how those platforms are, might not be easy. maybe should be a new node for that.

also, I'd like to see the subways have more seats.

**Comment by gbl08ma** [comment]
> has to be the advtrains platform

Yes, but this is a bit limiting, also the "instant jump" from the train to the platform isn't exactly smooth or natural. Of course, we all know how things would work "ideally": passengers could just walk in and out of the train depending on whether the doors are open or not... that not being possible, I guess we'll have to settle for formspec systems, keyboard shortcuts and "close enough".

**Comment by gpcf** [comment]
I think we could do without formspecs, but the jumps are harder to remove.

**Comment by gbl08ma** [comment]
My remark about formspecs was because I updated today, and while I greatly appreciate the improvements (you can finally ride _inside_ the trains!), I must say the mod keeps getting harder to use... now to leave a train I must either use the quite unnatural Shift+E (Sneak+Use), or right-click then select a menu option... kind of breaks the flow, also makes managing multiple runaway trains harder :smile: 

On the other hand, I definitely see the need to make the wagon properties and driver<->passenger switch easily accessible and discoverable (i.e. not behind yet another obscure shortcut...).

**Comment by gpcf** [comment]
Well, the seat selection formspec was removed, that was really inconvenient. I'll implement getting off with movement keys tomorrow.

**Comment by orwell96** [comment]
If you configure the driver stand to only allow players that are authorized (this is possible now), right_clicking won't show the menu anymore for normal clients (since there is only one possibility).

**Comment by orwell96** [comment]
closing the issue, will merge the PR ASAP.
