### ISSUE TITLE
Trains get randomly stuck

### ISSUE THREAD

**Issue by gbl08ma** [orwell96/advtrains#31]
As we began discussing on #27, trains randomly get stuck after looping in a ATC-controlled line for some minutes/hours. (It's possible it also happens without ATC, but I don't think anyone tested yet).

Furthermore, when a train unexpectedly stops and a queue of trains forms before it, sometimes trains overlap another instead of colliding and stopping before the one in front of them.

**Comment by orwell96** [comment]
Good that you opened the issue, as a ToDo reminder.
That's the next thing i need to resolve.

**Comment by orwell96** [comment]
Please try out if the problem still appears with the new version.

Note: Due to weirdnesses, the track database format was changed (for detailed info see the commit message of 328d505). For all trains to work properly in unloaded chunks, you need to walk, fly or drive along all places where tracks are laid a single time. By enabling debug info (Options/Mods/advtrains) and looking for the positions it complains and teleporting there, you can resolve most issues.
It may become necessary to visit all ATC rails and LuaAutomation components and click 'save' in order for them to work again. When fixing LuaAutomation components this way, the code may disappear first, exit form and reopen and the code will reappear (DO NOT click save twice!).

**Comment by orwell96** [comment]
Maybe it prints a warning about off-track now when a train stops unexpectedly.

**Comment by orwell96** [comment]
Please try if the problem still exists.

**Comment by gbl08ma** [comment]
Right now I have two trains running in a ATC-controlled line, they have been like this for some hours. They are yet to stop... I'll give it some more time and then this can be closed.

**Comment by orwell96** [comment]
I am letting my trains run over the night, if they still work tomorrow I agree.

**Comment by orwell96** [comment]
Looking at it right now, there are no issues.

**Comment by gpcf** [comment]
Report from the Linuxworks server: 3/3 Subway lines running!, for a couple of hours already, I'll report again tomorrow.

**Comment by orwell96** [comment]
Status report:
Lines 1 and 3 (signal controlled): work like a charm
Lines 2 and 5 (NOT signal controlled): Hung up at th wrongly oriented switches in the end stations (which was expectable, since the switch is switched wrong)
Line 4 (single train driving back and forth): works
seems like issue is fixed.

**Comment by orwell96** [comment]
Lines 1 and 3 (and 4) running for 24hrs now without problems.
Random stops were apparently caused by the train length occasionally exceeding the path, the same issue that was causing #35 and that is now fixed. That also explains why these problems didn't appear with path pregeneration length set to 10.

**Comment by orwell96** [comment]
(Line 1 - blue, Line 2 - red, Line 3 - yellow, Line 4 - green, Line 5 - purple on the itm_example.png, if you are interested which is which)

**Comment by gbl08ma** [comment]
If by "pregeneration length" you mean the value that was changed from 2 to
10 for the switch trick to work, then I'll let you know that even with that
value set to 10, trains were getting stuck.

I left the server running for about six hours, the trains did not stop. I
think this is fixed.
