### ISSUE TITLE
subways should be able to go through each other

### ISSUE THREAD

**Issue by ValkyrieStella** [orwell96/advtrains#32]
a huge issue on automatic rail lines is trains crashing into each other and creating a stoppage. couldn't you make subways be able to go right through another subway? and have a different mode/method for connecting.

**Comment by gbl08ma** [comment]
Just make sure all trains go at the same speed (on average), and make sure there's enough clearance between trains (the more variance there is between speeds, due to e.g. station stops, the more clearance you'll need to give).

I suppose that once ATC becomes more advanced it will be possible to do stuff like check what's the distance to the next train or at least check if there's a train in the next 50 or 100 blocks, so that trains going behind can adjust their speeds (slowing down if they are approaching a train in front of them). Much like what happens with real trains and signals, or people driving on a road, etc. Making the hack you suggest completely avoidable.

**Comment by ValkyrieStella** [comment]
no, not gonna work. no matter what i do something happens.

**Comment by orwell96** [comment]
there are problems with trains randomly stopping, I know that, see that other issue
Use the new lua rails to build sort of track section signalling.

**Comment by ValkyrieStella** [comment]
this would also be a good addition for the subways on atc's though. really. 

i have a circle with double tracks, one for one way and one for the other way. the trains on one track seem to behave yet on the other tracks i have tried for hours and days to get them working but they will just crash into each other.

**Comment by gbl08ma** [comment]
That actually sounds like it could be the same problem of #31. Are you sure the trains aren't randomly stopping, causing the ones behind them to crash into them?

**Comment by orwell96** [comment]
I am closing this since this is not really useful. If you want, you can just disable collisions by adding two dashes to trainlogic.lua line 70:
```
--advtrains.train_step_b(k, v, dtime)
```
