### ISSUE TITLE
lua ATC does not work in unloaded map chunks

### ISSUE THREAD

**Issue by gpcf** [orwell96/advtrains#33]
The lua ATC rails don't execute their code if they are in an unloaded chunk. They seem to be implemented differently from the other ones, that work in unloaded chunks.

**Comment by orwell96** [comment]
I recognized this issue myself. Now fixed.
See the new release and the notes on the forum.

**Comment by orwell96** [comment]
Note: Due to weirdnesses, the track database format was changed (for detailed info see the commit message of 328d505). For all trains to work properly in unloaded chunks, you need to walk, fly or drive along all places where tracks are laid a single time. By enabling debug info (Options/Mods/advtrains) and looking for the positions it complains and teleporting there, you can resolve most issues.
It may become necessary to visit all ATC rails and LuaAutomation components and click 'save' in order for them to work again. When fixing LuaAutomation components this way, the code may disappear first, exit form and reopen and the code will reappear (DO NOT click save twice!).
