### ISSUE TITLE
smoke

### ISSUE THREAD

**Issue by Desour** [orwell96/advtrains#6]
the trains could get an attached particlespawner to simulate smoke.
for turning i suggest attaching a new (invisible) entity, on which the particlespawner is attached, at the right position. (when the parent entity turns, attached entities turn around correctly, attached particlespawner not)

**Comment by orwell96** [comment]
what, attached particle spawners do not rotate with the entity?

**Comment by Desour** [comment]
yep, i thought of making an issue on minetest repo about it

**Comment by orwell96** [comment]
PR on its way

**Comment by orwell96** [comment]
Smoke implemented. It will only work with the git version from tomorrow. (or whenever my PR gets merged)

**Comment by Desour** [comment]
you could have used my way to attach an extra entity (and make it invisible and the selection box from 0 to 0, so that its unpointable and invisible)

**Comment by orwell96** [comment]
Attached particle spawners are a new feature found only in recent git versions, and my fix is useful, so why not. It wouldn't make a difference since almost no one should get a git version between "attached particle spawners" and my PR. Also, it would be much more (wasted) effort.
(I am pretty sure that it will get merged)
